#!/bin/bash


# Building topology info and saving input
cd ../Python\ Scripts
touch mainCSV.csv
py RouterConfigurator.py
rm ../Spine-Leaf-ManualDCN/_XHostSpineLeaf/ManualRoutingXML.xml
mv ManualRoutingXML.xml ../Spine-Leaf-ManualDCN/_XHostSpineLeaf/ManualRoutingXML.xml

#Creating New .ned file
py nedConfigurator.py

# For loop
for ((i=1; i<=$1; i++))
do
	echo $i
	# Creating Traffic based on topology input
	py SendScript.py < input.txt
	rm ../Spine-Leaf-ManualDCN/_XHostSpineLeaf/ini_generated.ini
	mv ini_generated.ini ../Spine-Leaf-ManualDCN/_XHostSpineLeaf/ini_generated.ini

	echo 'Starting Simulation'
	cd ../Spine-Leaf-ManualDCN

	#Running the simulation
	./Spine-LeafDCN.exe -u Cmdenv -f _XHostSpineLeaf/ini_generated.ini -c scriptTraffic

	# Converting results to .csv file
	echo 'Converting results file.'

	cd ./_XHostSpineLeaf/results
	scavetool x *.sca -o "run${i}.csv"
	mv "run${i}.csv" ../../../Python\ Scripts/

	# Running python script to display graphs
	echo 'Running graphing script.'

	cd ../../../
	pwd
	#py ResultsAnalysis.py
	#py ResultsAnalysisVec.py
	cd Python\ Scripts
	pwd


	#Stuff
	py csvMerger.py "run${i}.csv"
done

py ThroughputBoxPlot.py

rm *.csv
