#!/bin/bash


# Building topology info and saving input
cd ../Python\ Scripts
py RouterConfigurator.py
rm ../Spine-Leaf-ManualDCN/_XHostSpineLeaf/ManualRoutingXML.xml
mv ManualRoutingXML.xml ../Spine-Leaf-ManualDCN/_XHostSpineLeaf/ManualRoutingXML.xml

#Creating New .ned file
py nedConfigurator.py

# Creating Traffic based on topology input
py SendScript.py < input.txt
rm ../Spine-Leaf-ManualDCN/_XHostSpineLeaf/ini_generated.ini
mv ini_generated.ini ../Spine-Leaf-ManualDCN/_XHostSpineLeaf/ini_generated.ini

# Script to run simulation and display graphs.
echo 'Starting Simulation'
cd ../Spine-Leaf-ManualDCN

#Running the simulation
./Spine-LeafDCN.exe -u Cmdenv -f _XHostSpineLeaf/ini_generated.ini -c scriptTraffic

# Converting results to .csv file
echo 'Converting results file.'

cd ./_XHostSpineLeaf/results
scavetool x *.sca -o results.csv

# Running python script to display graphs
echo 'Running graphing script.'

cd ../../../
pwd
py ResultsAnalysis.py
py ResultsAnalysisVec.py
