//
// Generated file, do not edit! Created by nedtool 5.6 from inet/applications/pingapp/PingApp.msg.
//

#ifndef __INET_PINGAPP_M_H
#define __INET_PINGAPP_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API
#  endif
#endif


namespace inet {

} // namespace inet

#include "inet/common/INETDefs_m.h" // import inet.common.INETDefs


namespace inet {

/**
 * Enum generated from <tt>inet/applications/pingapp/PingApp.msg:22</tt> by nedtool.
 * <pre>
 * enum PingSelfKinds
 * {
 *     PING_FIRST_ADDR = 1001;
 *     PING_CHANGE_ADDR = 1002;
 *     PING_SEND = 1003;
 * }
 * </pre>
 */
enum PingSelfKinds {
    PING_FIRST_ADDR = 1001,
    PING_CHANGE_ADDR = 1002,
    PING_SEND = 1003
};

} // namespace inet

#endif // ifndef __INET_PINGAPP_M_H

